defmodule Apipe.Providers.OpenAPIEncoder do
  @moduledoc """
  Provides JSON encoding behavior for OpenAPI schemas generated by OpenAPI Generator (https://github.com/aj-foster/open-api-generator).
  """

  defmacro __using__(_opts) do
    quote do
      @derive {Jason.Encoder, except: [:__info__]}

      @doc """
      Casts a map to a struct.
      """
      def cast(data) when is_map(data) do
        # Get the list of fields defined in the struct
        fields = __MODULE__.__struct__() |> Map.keys() |> MapSet.new()

        # Only convert keys that exist in the struct
        atomized_data =
          data
          |> Enum.filter(fn {key, _} ->
            String.to_atom(key) in fields
          end)
          |> Enum.map(fn {k, v} -> {String.to_atom(k), v} end)
          |> Map.new()
          |> Map.put(:__info__, %{})
          |> Map.put(:__joins__, %{})

        result = struct(__MODULE__, atomized_data)
        {:ok, result}
      end
    end
  end
end
