defmodule GitHubOpenAPI.PublicUser do
  @moduledoc """
  Provides struct and type for a PublicUser
  """
  use Apipe.Providers.OpenAPI.Encoder

  @type t :: %__MODULE__{
          __info__: map,
          __joins__: map,
          avatar_url: String.t(),
          bio: String.t() | nil,
          blog: String.t() | nil,
          collaborators: integer | nil,
          company: String.t() | nil,
          created_at: DateTime.t(),
          disk_usage: integer | nil,
          email: String.t() | nil,
          events_url: String.t(),
          followers: integer,
          followers_url: String.t(),
          following: integer,
          following_url: String.t(),
          gists_url: String.t(),
          gravatar_id: String.t() | nil,
          hireable: boolean | nil,
          html_url: String.t(),
          id: integer,
          location: String.t() | nil,
          login: String.t(),
          name: String.t() | nil,
          node_id: String.t(),
          notification_email: String.t() | nil,
          organizations_url: String.t(),
          owned_private_repos: integer | nil,
          plan: GitHubOpenAPI.PublicUserPlan.t() | nil,
          private_gists: integer | nil,
          public_gists: integer,
          public_repos: integer,
          received_events_url: String.t(),
          repos_url: String.t(),
          site_admin: boolean,
          starred_url: String.t(),
          subscriptions_url: String.t(),
          total_private_repos: integer | nil,
          twitter_username: String.t() | nil,
          type: String.t(),
          updated_at: DateTime.t(),
          url: String.t(),
          user_view_type: String.t() | nil
        }

  defstruct [
    :__info__,
    :__joins__,
    :avatar_url,
    :bio,
    :blog,
    :collaborators,
    :company,
    :created_at,
    :disk_usage,
    :email,
    :events_url,
    :followers,
    :followers_url,
    :following,
    :following_url,
    :gists_url,
    :gravatar_id,
    :hireable,
    :html_url,
    :id,
    :location,
    :login,
    :name,
    :node_id,
    :notification_email,
    :organizations_url,
    :owned_private_repos,
    :plan,
    :private_gists,
    :public_gists,
    :public_repos,
    :received_events_url,
    :repos_url,
    :site_admin,
    :starred_url,
    :subscriptions_url,
    :total_private_repos,
    :twitter_username,
    :type,
    :updated_at,
    :url,
    :user_view_type
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      avatar_url: {:string, :uri},
      bio: {:string, :generic},
      blog: {:string, :generic},
      collaborators: :integer,
      company: {:string, :generic},
      created_at: {:string, :date_time},
      disk_usage: :integer,
      email: {:string, :email},
      events_url: {:string, :generic},
      followers: :integer,
      followers_url: {:string, :uri},
      following: :integer,
      following_url: {:string, :generic},
      gists_url: {:string, :generic},
      gravatar_id: {:string, :generic},
      hireable: :boolean,
      html_url: {:string, :uri},
      id: :integer,
      location: {:string, :generic},
      login: {:string, :generic},
      name: {:string, :generic},
      node_id: {:string, :generic},
      notification_email: {:string, :email},
      organizations_url: {:string, :uri},
      owned_private_repos: :integer,
      plan: {GitHubOpenAPI.PublicUserPlan, :t},
      private_gists: :integer,
      public_gists: :integer,
      public_repos: :integer,
      received_events_url: {:string, :uri},
      repos_url: {:string, :uri},
      site_admin: :boolean,
      starred_url: {:string, :generic},
      subscriptions_url: {:string, :uri},
      total_private_repos: :integer,
      twitter_username: {:string, :generic},
      type: {:string, :generic},
      updated_at: {:string, :date_time},
      url: {:string, :uri},
      user_view_type: {:string, :generic}
    ]
  end
end
